### ISSUE TITLE
add a namespace for each configuration file

### ISSUE THREAD

**Issue by Pathjana** [Pathangi-Jatinshravan/Network_Topology#3]
When doing create it is difficult to keep unique names across multiple runs when the previous runs are still active. also most  of the times, the simplest names are things like h1, n1, m1 etc. and repeating this in another config file causes problems.

it would be good to have the script, append or postpend some unique characters to these while still allowing the user to deal with the above names in the command line and conf file. probably just create a namespace per run and have that stored in the resources file.

**Comment by jatin-pathangi** [comment]
Done

**Comment by Pathjana** [comment]
two things that would be nice to be fixed:
1. In the initialization if you can initialize the namespace with the pid rather than "", than in case the user does not specify a namespace, the PID gets added as a namespace that will ensure a fair level of uniquness
2. The bridge names also need to be put into this same namespace.

**Comment by jatin-pathangi** [comment]
Done
