### ISSUE TITLE
open vswitch bridge does not work

### ISSUE THREAD

**Issue by Pathjana** [Pathangi-Jatinshravan/Network_Topology#5]
When I do not specify anything in the config file for the  bridge (i.e. default to openvswitch), I get the following errors:
# sudo ./nw_topo.py --directory /home/jana/ospf_topo create

[u'mgmt_ja_', u'dummy_ja_', u'link6_ja_', u'link1_ja_', u'link2_ja_', u'link5_ja_', u'link3_ja_', u'link4_ja_']
error: Failed to define network from conf/net.xml
error: unsupported configuration: unknown virtualport type ovsbridge

error: failed to get network 'mgmt_ja_'
error: Network not found: no network with matching name 'mgmt_ja_'

error: failed to get network 'mgmt_ja_'
error: Network not found: no network with matching name 'mgmt_ja_'

error: Failed to define network from conf/net.xml
error: unsupported configuration: unknown virtualport type ovsbridge
.....

**Comment by jatin-pathangi** [comment]
Fixed
