### ISSUE TITLE
error checking in the various functions for resource.json file

### ISSUE THREAD

**Issue by Pathjana** [Pathangi-Jatinshravan/Network_Topology#8]
move the error checking of the resource.file related stuff to the main code before calling the individual function like clean, console, restart etc. so that these can be handled in one single space and not repeated again.

**Comment by jatin-pathangi** [comment]
This can be done, but the error messages given by different functions are different. For example cleanup says 'Nothing to clean' whereas console() says 'No VMs created, please create VMs before running with this option'.

**Comment by Pathjana** [comment]
true, but you can make this as a slightly generic message say something like "There is no resources created. Run create before calling this function".

**Comment by Pathjana** [comment]
the above is a generic error that you can give in the main code. While the specific functons can give more detailed error, for e.g. if the user specifies a VM name in the console and there is no such VM, than the console function can print saying that invalid VM name,.

**Comment by jatin-pathangi** [comment]
Done
